import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.css";
import NavHeader from "@/components/NavHeader";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Gibbon",
  description: "Generated by Gibbon app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-white text-gray-900 overflow-x-hidden">
          <NavHeader />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
